name: myosa_app
description: Myosa Gait Monitor Companion App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.8.3
  syncfusion_flutter_charts: ^22.1.40
  pdf: ^3.10.1
  printing: ^5.9.1
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  vibration: ^1.8.4
  url_launcher: ^6.2.1
  permission_handler: ^10.4.0

flutter:
  uses-material-design: true